


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgaudit" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."acred_type" AS ENUM (
    'a',
    'ab',
    'MrS',
    'Mna',
    'b',
    'c',
    'd',
    'e',
    'f'
);


CREATE TYPE "public"."clase_type" AS ENUM (
    'MICROBIOLOGICO',
    'FISICOQUIMICOS',
    'RESIDUOS QUIMICOS',
    'FERTILIZACION',
    'FITOSANIDAD',
    'MIGRACION QUIMICA',
    'OTROS'
);

CREATE TYPE "public"."divisa_type" AS ENUM (
    'USD',
    'EUR',
    'MXN'
);


COMMENT ON TYPE "public"."clase_type" IS 'clase valores para la tabla catAnalisis';



CREATE TYPE "public"."cobertura_type" AS ENUM (
    'Internacional - IFC',
    'Nacional - IFC LABS'
);


COMMENT ON TYPE "public"."cobertura_type" IS 'cobertura values para tabla catAnalisis';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Archivo_Analisis" (
    "id" integer NOT NULL,
    "id_analisis" character varying,
    "uuid_archivo" "uuid"
);


COMMENT ON TABLE "public"."Archivo_Analisis" IS 'Relacional, los archivos de un analisis';



ALTER TABLE "public"."Archivo_Analisis" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Archivo_Analisis_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Area_Usuario" (
    "user_id" "uuid" NOT NULL,
    "area_id" bigint NOT NULL
);


COMMENT ON TABLE "public"."Area_Usuario" IS 'Area X Usuario, join table';



CREATE TABLE IF NOT EXISTS "public"."areas" (
    "id" integer NOT NULL,
    "area" "text" NOT NULL,
    "descripcion" "text" NOT NULL
);


COMMENT ON TABLE "public"."areas" IS 'Areas core table';



ALTER TABLE "public"."areas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."areas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."catAnalisis" (
    "id_analisis" character varying DEFAULT ''::character varying NOT NULL,
    "y_cantidad" integer DEFAULT 1,
    "c_costo" real DEFAULT '0'::real,
    "c_envio" real DEFAULT '0'::real,
    "y_cobertura" "public"."cobertura_type",
    "y_clase" "public"."clase_type",
    "desc_toptext" "text",
    "desc_metodo" "text",
    "desc_muestra_tipo" "text",
    "desc_bottomtext" "text",
    "desc_respuesta" "text",
    "c_factor" real DEFAULT '1'::real,
    "desc_muestra_cantd" "text",
    "y_precio" numeric(10,2) GENERATED ALWAYS AS (COALESCE((("c_costo" * "c_factor") + "c_envio"), (0)::real)) STORED,
    "c_utilidad" numeric(10,2) GENERATED ALWAYS AS (COALESCE((("c_costo" * ("c_factor" - (1)::double precision)) * ("y_cantidad")::double precision), (0)::double precision)) STORED,
    "id_catLabos" "text"
);

ALTER TABLE ONLY "public"."catAnalisis" REPLICA IDENTITY FULL;



COMMENT ON TABLE "public"."catAnalisis" IS 'Analisis table, from Catalog';



COMMENT ON COLUMN "public"."catAnalisis"."c_costo" IS 'cyan . costo (la cantidad base';



COMMENT ON COLUMN "public"."catAnalisis"."desc_metodo" IS 'descripcion . metodologia ... usualmente nombre, el texto al inicio de la descripcion';



COMMENT ON COLUMN "public"."catAnalisis"."desc_bottomtext" IS 'usualmente notas, mezcla entre indicaciones especiales y comentarios del editor';



CREATE TABLE IF NOT EXISTS "public"."catLabos" (
    "nombre_lab" "text" NOT NULL,
    "pais_lab" "text" DEFAULT 'Sin país'::"text",
    "divisa_lab" "public"."divisa_type" NOT NULL DEFAULT 'MXN'::divisa_type,
    "direccion_lab" "text" DEFAULT 'Sin dirección'::"text",
    "contacto_lab" "text" DEFAULT 'Sin contacto'::"text"
);

ALTER TABLE ONLY "public"."catLabos" REPLICA IDENTITY FULL;



COMMENT ON TABLE "public"."catLabos" IS 'Lab info table, from Catalog';



CREATE TABLE IF NOT EXISTS "public"."catStatics" (
    "id" integer NOT NULL,
    "marker" "text" NOT NULL,
    "value" real
);


COMMENT ON TABLE "public"."catStatics" IS 'Static data, from Catalog';



ALTER TABLE ONLY "public"."Archivo_Analisis"
    ADD CONSTRAINT "Archivo_Analisis_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Archivo_Analisis"
    ADD CONSTRAINT "Archivo_Analisis_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Archivo_Analisis"
    ADD CONSTRAINT "Archivo_Analisis_uuid_archivo_key" UNIQUE ("uuid_archivo");



ALTER TABLE ONLY "public"."Area_Usuario"
    ADD CONSTRAINT "Area_Usuario_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."catAnalisis"
    ADD CONSTRAINT "catAnalisis_id_analisis_key" UNIQUE ("id_analisis");



ALTER TABLE ONLY "public"."catAnalisis"
    ADD CONSTRAINT "catAnalisis_pkey" PRIMARY KEY ("id_analisis");



ALTER TABLE ONLY "public"."catLabos"
    ADD CONSTRAINT "catLabos_nombre_lab_key" UNIQUE ("nombre_lab");



ALTER TABLE ONLY "public"."catLabos"
    ADD CONSTRAINT "catLabos_pkey" PRIMARY KEY ("nombre_lab");



ALTER TABLE ONLY "public"."catStatics"
    ADD CONSTRAINT "catStatics_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."catStatics"
    ADD CONSTRAINT "catStatics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."catStatics"
    ADD CONSTRAINT "static_values_marker_key" UNIQUE ("marker");



ALTER TABLE ONLY "public"."Archivo_Analisis"
    ADD CONSTRAINT "Archivo_Analisis_id_analisis_fkey" FOREIGN KEY ("id_analisis") REFERENCES "public"."catAnalisis"("id_analisis") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Archivo_Analisis"
    ADD CONSTRAINT "Archivo_Analisis_uuid_archivo_fkey" FOREIGN KEY ("uuid_archivo") REFERENCES "storage"."objects"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Area_Usuario"
    ADD CONSTRAINT "Area_Usuario_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."Area_Usuario"
    ADD CONSTRAINT "Area_Usuario_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."catAnalisis"
    ADD CONSTRAINT "catAnalisis_id_catLabos_fkey" FOREIGN KEY ("id_catLabos") REFERENCES "public"."catLabos"("nombre_lab") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow to only Get the current user's role" ON "public"."Area_Usuario" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."Archivo_Analisis" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Area_Usuario" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable DELETE for AUTHED area.id = 1" ON "public"."catLabos" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND ("a"."id" = 1)))));



CREATE POLICY "Enable DELETE for AUTHED area.id=1 " ON "public"."catAnalisis" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = "auth"."uid"()) AND ("a"."id" = 1)))));



CREATE POLICY "Enable DELETE for AUTHEDS area.id = 1" ON "public"."Archivo_Analisis" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = "auth"."uid"()) AND ("a"."id" = 1)))));



CREATE POLICY "Enable INSERT for AUTHED area.id = 1" ON "public"."Archivo_Analisis" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = "auth"."uid"()) AND ("a"."id" = 1)))));



CREATE POLICY "Enable INSERT for AUTHED area.id = 1" ON "public"."catLabos" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND ("a"."id" = 1)))));



CREATE POLICY "Enable INSERT for AUTHED area.id=1 " ON "public"."catAnalisis" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = "auth"."uid"()) AND ("a"."id" = 1)))));



CREATE POLICY "Enable READ for AUTHEDS" ON "public"."catAnalisis" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable READ for all AUTHEDS" ON "public"."Archivo_Analisis" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable UPDATE for AUTHED area.id = 1" ON "public"."catLabos" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND ("a"."id" = 1)))));



CREATE POLICY "Enable UPDATE for AUTHED area.id=1 " ON "public"."catAnalisis" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."Area_Usuario" "au"
     JOIN "public"."areas" "a" ON (("a"."id" = "au"."area_id")))
  WHERE (("au"."user_id" = "auth"."uid"()) AND ("a"."id" = 1)))));



CREATE POLICY "Enable read access for authed users" ON "public"."catLabos" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authed users" ON "public"."catStatics" FOR SELECT USING (true);



CREATE POLICY "Enable read for authed users" ON "public"."areas" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."areas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."catAnalisis" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."catLabos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."catStatics" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."catAnalisis";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."catLabos";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON FUNCTION "public"."pgaudit_ddl_command_end"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgaudit_ddl_command_end"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgaudit_ddl_command_end"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgaudit_ddl_command_end"() TO "service_role";



GRANT ALL ON FUNCTION "public"."pgaudit_sql_drop"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgaudit_sql_drop"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgaudit_sql_drop"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgaudit_sql_drop"() TO "service_role";


















GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Archivo_Analisis" TO "postgres";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Archivo_Analisis" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Archivo_Analisis" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Archivo_Analisis" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Archivo_Analisis_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."Archivo_Analisis_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Archivo_Analisis_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Archivo_Analisis_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Area_Usuario" TO "postgres";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Area_Usuario" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Area_Usuario" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."Area_Usuario" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."areas" TO "postgres";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."areas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."areas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."areas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."areas_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."areas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."areas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."areas_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catAnalisis" TO "postgres";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catAnalisis" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catAnalisis" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catAnalisis" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catLabos" TO "postgres";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catLabos" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catLabos" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catLabos" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catStatics" TO "postgres";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catStatics" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catStatics" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."catStatics" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";































